#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="${1:-.}"

need() { command -v "$1" >/dev/null 2>&1 || { echo "$1 not found in PATH" >&2; exit 1; }; }
need git
need codex

agent="$(cat "$REPO_ROOT/codex/AGENT_PROMPT.md")"
tasks="$(cat "$REPO_ROOT"/codex/TASKS/*.md | sed 's/\r$//')"
repo_info="$(git ls-files; echo; git status --porcelain)"

mkdir -p "$REPO_ROOT/.codex"
tmp_in="$REPO_ROOT/.codex/in.txt"
tmp_out="$REPO_ROOT/.codex/out.txt"
patch="$REPO_ROOT/.codex/diff.patch"

{
  echo "$agent"
  echo
  echo "CONTEXT:"
  echo "Repository file list (git ls-files):"
  echo "$repo_info"
  echo
  echo "TASKS (markdown):"
  echo "$tasks"
} > "$tmp_in"

codex < "$tmp_in" > "$tmp_out"

if [ ! -s "$tmp_out" ]; then
  echo "No diff returned. Nothing to do."
  exit 0
fi

if grep -qn "^diff --git " "$tmp_out"; then
  awk 'f||/^diff --git /{f=1;print}' "$tmp_out" > "$patch"
elif grep -qn "^--- " "$tmp_out"; then
  awk 'f||/^--- /{f=1;print}' "$tmp_out" > "$patch"
else
  echo "No unified diff header found in Codex output." >&2
  exit 1
fi

branch="codex/task-$(date +%Y%m%d-%H%M%S)"
git checkout -b "$branch"
git apply --whitespace=fix "$patch"
git add -A
git commit -m "[codex] automated patch"
git push -u origin "$branch"

if command -v gh >/dev/null 2>&1; then
  gh pr create --title "[codex] automated patch" --body "Generated by Codex CLI runner."
else
  echo "Branch pushed: $branch. Create a PR manually."
fi
