Param(
  [string]$RepoRoot = "."
)
$ErrorActionPreference = "Stop"

function Need($cmd) {
  if (-not (Get-Command $cmd -ErrorAction SilentlyContinue)) {
    Write-Error "$cmd not found in PATH."
  }
}
Need "git"
Need "codex"

$agent = Get-Content "$RepoRoot/codex/AGENT_PROMPT.md" -Raw
$tasks = (Get-ChildItem "$RepoRoot/codex/TASKS" -Filter "*.md" | Sort-Object Name | ForEach-Object { Get-Content $_.FullName -Raw }) -join "`n---`n"
$repoInfo = (& git ls-files) -join "`n"
$changes = (& git status --porcelain) -join "`n"

$full = @"
$agent

CONTEXT:
Repository file list (git ls-files):
$repoInfo

Pending changes (git status --porcelain):
$changes

TASKS (markdown):
$tasks
"@

# Unique temp files per run
$tempDir = Join-Path $RepoRoot ".codex"
New-Item -ItemType Directory -Force -Path $tempDir | Out-Null
$runId = [System.Guid]::NewGuid().ToString("N")
$tmpIn  = Join-Path $tempDir ("in_{0}.txt" -f $runId)
$tmpOut = Join-Path $tempDir ("out_{0}.txt" -f $runId)
$patch  = Join-Path $tempDir ("diff_{0}.patch" -f $runId)

Set-Content -Path $tmpIn -Value $full -Encoding ASCII

# Capture CLI output in memory to avoid locking
# Adjust 'codex' if your CLI needs a subcommand.
$resp = Get-Content $tmpIn -Raw | codex

if (-not $resp -or $resp.Trim().Length -eq 0) {
  Write-Output "No diff returned. Nothing to do."
  exit 0
}
Set-Content -Path $tmpOut -Value $resp -Encoding ASCII

# Extract a unified diff starting at "diff --git" or "--- "
$content = Get-Content $tmpOut -Raw
$lines = $content -split "`r?`n"
$start = ($lines | Select-String -SimpleMatch "diff --git").LineNumber
if (-not $start) { $start = ($lines | Select-String -Pattern "^\-\-\- ").LineNumber }
if (-not $start) { Write-Error "No unified diff header found in Codex output." }

$usable = ($lines[($start-1)..($lines.Length-1)]) -join "`n"
Set-Content -Path $patch -Value $usable -Encoding ASCII

# Create branch, apply patch, push, PR
$branch = "codex/task-" + (Get-Date -Format "yyyyMMdd-HHmmss")
git checkout -b $branch
git apply --whitespace=fix "$patch"
git add -A
git commit -m "[codex] automated patch"
git push -u origin $branch

if (Get-Command gh -ErrorAction SilentlyContinue) {
  gh pr create --title "[codex] automated patch" --body "Generated by Codex CLI runner."
} else {
  Write-Output "Branch pushed: $branch. Create a PR manually."
}
