name: codex-agent
on:
  workflow_dispatch:
  schedule:
    - cron: "15 * * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  run-agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup git identity
        run: |
          git config user.name "codex-bot"
          git config user.email "codex-bot@users.noreply.github.com"
      - name: Install Codex CLI
        run: npm i -g @openai/codex
      - name: Run agent
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash ./codex/run_agent.sh .
